platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: 'v16.1.0'

inputs:
  - name: cf-performance-tests-pipeline

outputs:
  - name: cf-vars-file

run:
  path: cf-performance-tests-pipeline/ci/tasks/write-bosh-vars-file/task.sh

params:
  VARS:
